/**
 * plugin.json (.claude-plugin/plugin.json). GENERATED by skillsmith (I1/I2) —
 * this schema exists to validate our own output and third-party plugins.
 *
 * Claude Code's own tolerance: unrecognized fields are warnings, not errors
 * (so one manifest can double as an npm/VS Code manifest). We match that.
 * Ground truth is the CLI validator, not published JSON Schemas (they diverge).
 */
import { z } from "zod";
import { KEBAB_CASE } from "../constants.ts";
import {
  type Diagnostic,
  type ValidationResult,
  error,
  warning,
} from "../diagnostics.ts";

const SEMVER =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

export const authorSchema = z.looseObject({
  name: z.string().min(1),
  email: z.string().optional(),
  url: z.string().optional(),
});

const pathOrPaths = z.union([z.string(), z.array(z.string())]);

export const pluginManifestSchema = z.looseObject({
  /** The only hard-required field. */
  name: z.string().min(1).regex(KEBAB_CASE, "plugin name must be kebab-case"),
  version: z.string().regex(SEMVER, "version must be semver").optional(),
  description: z.string().optional(),
  author: authorSchema.optional(),
  homepage: z.string().optional(),
  repository: z.string().optional(),
  license: z.string().optional(),
  keywords: z.array(z.string()).optional(),
  // Path overrides. These SUPPLEMENT defaults — except `agents`, which must
  // be an array of file paths (Claude Code quirk, verified).
  commands: pathOrPaths.optional(),
  agents: z.array(z.string()).optional(),
  skills: pathOrPaths.optional(),
  hooks: z.union([z.string(), z.unknown()]).optional(),
  mcpServers: z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  outputStyles: pathOrPaths.optional(),
  lspServers: z.union([z.string(), z.unknown()]).optional(),
});

export type PluginManifest = z.infer<typeof pluginManifestSchema>;

const KNOWN_FIELDS = new Set([
  "name",
  "version",
  "description",
  "author",
  "homepage",
  "repository",
  "license",
  "keywords",
  "commands",
  "agents",
  "skills",
  "hooks",
  "mcpServers",
  "outputStyles",
  "lspServers",
]);

export function validatePluginManifest(
  raw: unknown,
  ctx: { path: string },
): ValidationResult<PluginManifest> {
  const diagnostics: Diagnostic[] = [];
  const parsed = pluginManifestSchema.safeParse(raw);

  if (!parsed.success) {
    for (const issue of parsed.error.issues) {
      diagnostics.push(
        error("SCHEMA", `${ctx.path}#/${issue.path.join("/")}`, issue.message, [
          "claude-code",
          "cowork",
        ]),
      );
    }
    return { diagnostics };
  }

  const manifest = parsed.data;

  for (const key of Object.keys(manifest)) {
    if (!KNOWN_FIELDS.has(key)) {
      diagnostics.push(
        warning(
          "SCHEMA",
          `${ctx.path}#/${key}`,
          `unrecognized manifest field "${key}" (Claude Code treats this as a warning)`,
          ["claude-code"],
        ),
      );
    }
  }

  if (manifest.version === undefined) {
    diagnostics.push(
      warning(
        "SCHEMA",
        `${ctx.path}#/version`,
        "no version — semver is contractual for a public marketplace (consumers pin against you)",
      ),
    );
  }

  return { value: manifest, diagnostics };
}
