/**
 * Catalog — CATALOG.md is the marketplace's public homepage surface (spec §3
 * `doc`). v0.1 renders from frontmatter + config; eval pass-rates and token
 * budgets join when `eval`/`budget` land (their columns are present now so
 * the format is stable).
 */
import type { DiscoveryResult, DiscoveredSkill } from "./discovery.ts";
import type { SkillsmithConfig } from "./schemas/skillsmith-config.ts";
import type { ScriptInventoryEntry } from "./validate.ts";
import type { EvalResultsFile } from "./eval.ts";
import type { CompositionEdge } from "./composition.ts";

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");

/** Codepoint order, NOT localeCompare: catalog output must be byte-identical
 * across platforms or the drift gate fails when CI (Linux ICU) and an author's
 * machine (e.g. Windows ICU) disagree on locale-aware ordering of hyphenated
 * names. The rest of the pipeline sorts the same way (plain `.sort()`). */
const byCodepoint = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

export function renderCatalog(
  shipped: { skill: DiscoveredSkill; plugin: string }[],
  discovery: DiscoveryResult,
  config: SkillsmithConfig,
  inventories?: Map<string, ScriptInventoryEntry[]>,
  evalResults?: EvalResultsFile,
  edges?: CompositionEdge[],
): string {
  const lines: string[] = [];
  lines.push(`# ${config.marketplace.name} — Catalog`);
  lines.push("");
  lines.push(
    "> GENERATED by skillsmith — do not edit. Source of truth: `skills/` frontmatter + `skillsmith.toml`.",
  );
  lines.push("");

  const byPlugin = new Map<string, { skill: DiscoveredSkill; plugin: string }[]>();
  for (const entry of shipped) {
    const list = byPlugin.get(entry.plugin) ?? [];
    list.push(entry);
    byPlugin.set(entry.plugin, list);
  }

  for (const grouping of [...config.plugin].sort((a, b) =>
    byCodepoint(a.name, b.name),
  )) {
    lines.push(`## ${grouping.name}`);
    if (grouping.description) {
      lines.push("");
      lines.push(grouping.description);
    }
    lines.push("");
    const badges = evalResults !== undefined;
    lines.push(
      badges
        ? "| Skill | Category | Invocation | Maturity | Triggering | Description |"
        : "| Skill | Category | Invocation | Maturity | Description |",
    );
    lines.push(badges ? "|---|---|---|---|---|---|" : "|---|---|---|---|---|");
    const entries = (byPlugin.get(grouping.name) ?? []).sort((a, b) =>
      byCodepoint(a.skill.name, b.skill.name),
    );
    for (const { skill } of entries) {
      const meta = skill.frontmatter.metadata ?? {};
      const evalCell = (() => {
        const r = evalResults?.skills[skill.name];
        if (!r) return "—";
        return `${Math.round(r.hitRate * 100)}% (${r.cases - r.failing}/${r.cases}, ${evalResults!.judgeModel}, ${evalResults!.runDate})`;
      })();
      lines.push(
        badges
          ? `| ${esc(skill.name)} | ${esc(skill.category)} | ${esc(meta["skillsmith-invocation"] ?? "model")} | ${esc(meta["skillsmith-maturity"] ?? "experimental")} | ${esc(evalCell)} | ${esc(skill.frontmatter.description)} |`
          : `| ${esc(skill.name)} | ${esc(skill.category)} | ${esc(meta["skillsmith-invocation"] ?? "model")} | ${esc(meta["skillsmith-maturity"] ?? "experimental")} | ${esc(skill.frontmatter.description)} |`,
      );
    }
    if (grouping.agents.length > 0) {
      lines.push("");
      lines.push(`Agents: ${[...grouping.agents].sort().join(", ")}`);
    }
    if (grouping.hooks.length > 0) {
      lines.push("");
      lines.push(`Hooks: ${[...grouping.hooks].sort().join(", ")}`);
    }
    if (grouping.mcp.length > 0) {
      lines.push("");
      lines.push(`MCP servers: ${[...grouping.mcp].sort().join(", ")}`);
    }

    const pluginSkillNames = new Set(entries.map((e) => e.skill.name));
    const pluginEdges = (edges ?? []).filter((e) => pluginSkillNames.has(e.composer));
    if (pluginEdges.length > 0) {
      lines.push("");
      lines.push(
        `Composes: ${pluginEdges
          .map((e) => `${e.composer} → ${e.target}${e.crossPlugin ? " (cross-plugin)" : ""}`)
          .join("; ")}`,
      );
    }

    // S1: provenance — what will execute, verifiable by hash.
    const inventoryRows = entries.flatMap(({ skill }) =>
      (inventories?.get(skill.name) ?? []).map((entry) => ({ skill: skill.name, entry })),
    );
    if (inventoryRows.length > 0) {
      lines.push("");
      lines.push("### What will execute (script inventory)");
      lines.push("");
      lines.push("| Skill | Script | Interpreter | Network | SHA-256 |");
      lines.push("|---|---|---|---|---|");
      for (const { skill, entry } of inventoryRows) {
        lines.push(
          `| ${esc(skill)} | ${esc(entry.path)} | ${esc(entry.interpreter)} | ${entry.networkTouching ? "yes" : "no"} | \`${entry.sha256.slice(0, 16)}…\` |`,
        );
      }
    }
    lines.push("");
  }

  const draftCount = discovery.skills.filter((s) => s.draft).length;
  if (draftCount > 0) {
    lines.push(`*${draftCount} draft skill(s) in progress (not shipped).*`);
    lines.push("");
  }

  return lines.join("\n");
}
